/**
 * Portfolio Create Function
 * 
 * Creates a new portfolio item with pre-generated AI content
 * Screenshot capture happens on PUBLISH (see portfolio-publish.js)
 */

import { createPortfolioItem } from '../../src/lib/portfolio-admin.js'
import { createClient } from '@supabase/supabase-js'
import { getAuthenticatedUser } from './utils/supabase.js'

const supabase = createClient(
  process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
)

export async function handler(event) {
  // Only allow POST requests
  if (event.httpMethod !== 'POST') {
    return {
      statusCode: 405,
      body: JSON.stringify({ error: 'Method not allowed' })
    }
  }

  try {
    // 1. Verify authentication using Supabase
    const { user, contact, error: authError } = await getAuthenticatedUser(event)
    if (authError || !contact) {
      return {
        statusCode: 401,
        body: JSON.stringify({ error: 'Unauthorized' })
      }
    }
    
    // 2. Check admin role
    if (contact.role !== 'admin') {
      return {
        statusCode: 403,
        body: JSON.stringify({ error: 'Admin privileges required' })
      }
    }

    // 3. Parse request body
    const data = JSON.parse(event.body)

    // Check if this is a new flow (pre-generated content) or legacy flow
    const isNewFlow = data.subtitle && data.services_showcase

    if (isNewFlow) {
      // New flow: content already generated by portfolio-ai-generate
      return await createPortfolioWithPregenerated(data)
    } else {
      // Legacy flow: use createPortfolioItem which generates AI content
      return await createPortfolioLegacy(data)
    }

  } catch (error) {
    console.error('[Portfolio API] Error:', error)
    return {
      statusCode: 500,
      body: JSON.stringify({
        error: error.message,
        message: 'Failed to create portfolio item'
      })
    }
  }
}

// New flow: Insert pre-generated content directly
async function createPortfolioWithPregenerated(data) {
  const {
    // Basic info
    companyName,
    websiteUrl,
    industry,
    location,
    category,
    servicesProvided,
    
    // Pre-generated content
    title,
    subtitle,
    description,
    slug,
    kpis,
    services_showcase,
    strategic_approach,
    technical_innovations,
    comprehensive_results,
    challenges,
    testimonial,
    gallery,
    video,
    team,
    tech_stack,
    content,
    seo,
    details,
    
    // Status
    status = 'draft'
  } = data

  // Generate slug if not provided
  const finalSlug = slug || companyName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')

  console.log(`[Portfolio API] Creating portfolio with pre-generated content: ${companyName}`)

  // Check for duplicate slug
  const { data: existing } = await supabase
    .from('portfolio_items')
    .select('slug')
    .eq('slug', finalSlug)
    .single()

  if (existing) {
    return {
      statusCode: 400,
      body: JSON.stringify({ error: `Portfolio item with slug "${finalSlug}" already exists` })
    }
  }

  // Prepare record
  const portfolioRecord = {
    slug: finalSlug,
    title: title || companyName,
    subtitle: subtitle || '',
    category: category || industry,
    services: servicesProvided || [],
    description: description || '',
    
    // Placeholder image - will be updated after screenshot
    hero_image: '/portfolio-previews/placeholder.jpg',
    hero_image_alt: `${companyName} website showcase`,
    hero_image_width: null,
    hero_image_height: null,
    
    // Website URL
    live_url: websiteUrl,
    
    // Pre-generated blocks
    kpis: kpis || null,
    services_showcase: services_showcase || null,
    strategic_approach: strategic_approach || null,
    comprehensive_results: comprehensive_results || null,
    technical_innovations: technical_innovations || null,
    challenges: challenges || null,
    testimonial: testimonial || null,
    gallery: gallery || null,
    video: video || null,
    team: team || null,
    technologies: tech_stack || null,
    
    // Details
    details: details || {
      industry: industry,
      location: location,
      website: websiteUrl
    },
    
    // SEO
    seo: seo || null,
    
    // Content
    content: content || '',
    content_html: null,
    
    // Publishing
    status: status,
    featured: false,
    order: 0,
    published_at: status === 'published' ? new Date().toISOString() : null
  }

  // Insert into database
  console.log('[Portfolio API] Inserting into database...')
  const { data: insertedItem, error: insertError } = await supabase
    .from('portfolio_items')
    .insert(portfolioRecord)
    .select()
    .single()

  if (insertError) {
    console.error('[Portfolio API] Database error:', insertError)
    return {
      statusCode: 500,
      body: JSON.stringify({ error: insertError.message })
    }
  }

  console.log(`[Portfolio API] Portfolio created with ID: ${insertedItem.id}`)

  return {
    statusCode: 200,
    body: JSON.stringify({
      success: true,
      data: insertedItem,
      message: `Portfolio item "${companyName}" created as ${status}. ${status === 'published' ? 'Screenshot capture started.' : 'Publish to capture screenshot.'}`,
      previewUrl: `https://uptrademedia.com/portfolio/${finalSlug}/`,
      trifolioUrl: `https://uptrademedia.com/portfolio/${finalSlug}/trifolio/`
    })
  }
}

// Legacy flow: Use the original createPortfolioItem function
async function createPortfolioLegacy(formData) {
  // Validate required fields for legacy flow
  const required = [
    'companyName',
    'websiteUrl',
    'industry',
    'location',
    'servicesProvided',
    'projectGoals',
    'challengesSolved',
    'targetAudience'
  ]

  for (const field of required) {
    if (!formData[field]) {
      return {
        statusCode: 400,
        body: JSON.stringify({
          error: `Missing required field: ${field}`
        })
      }
    }
  }

  console.log('[Portfolio API] Creating portfolio item (legacy flow) for:', formData.companyName)
  const result = await createPortfolioItem(formData)

  return {
    statusCode: result.success ? 200 : 500,
    body: JSON.stringify(result)
  }
}
