// src/components/sync/SignalAIPanel.jsx
// AI-powered features panel for Sync module
// Only shown when Signal is enabled for the org

import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  Sparkles,
  Brain,
  Clock,
  Target,
  Calendar,
  RefreshCw,
  ChevronDown,
  ChevronUp,
  Play,
  Pause,
  CheckCircle,
  AlertCircle,
  Lightbulb,
  Zap,
  User,
  FileText,
  ExternalLink,
  Coffee
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Separator } from '@/components/ui/separator'
import { cn } from '@/lib/utils'
import { syncApi } from '@/lib/signal-api'
import useAuthStore from '@/lib/auth-store'

// ============================================================================
// DAILY BRIEFING COMPONENT
// ============================================================================

function DailyBriefing({ data, loading, onRefresh }) {
  const [expanded, setExpanded] = useState(true)
  
  if (loading) {
    return (
      <Card className="border-primary/20 bg-primary/5">
        <CardContent className="py-4">
          <div className="flex items-center gap-2">
            <RefreshCw className="h-4 w-4 animate-spin text-primary" />
            <span className="text-sm">Loading your briefing...</span>
          </div>
        </CardContent>
      </Card>
    )
  }
  
  return (
    <Card className="border-primary/20 bg-gradient-to-br from-primary/5 to-transparent">
      <CardHeader className="py-3 px-4">
        <div 
          className="flex items-center justify-between cursor-pointer"
          onClick={() => setExpanded(!expanded)}
        >
          <div className="flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-primary" />
            <CardTitle className="text-sm font-medium">Daily Briefing</CardTitle>
          </div>
          <Button variant="ghost" size="icon" className="h-6 w-6">
            {expanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
          </Button>
        </div>
      </CardHeader>
      
      <AnimatePresence>
        {expanded && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
          >
            <CardContent className="pt-0 pb-4 px-4">
              {data?.summary ? (
                <div className="space-y-3">
                  <p className="text-sm text-muted-foreground leading-relaxed">
                    {data.summary}
                  </p>
                  
                  {data.highlights?.length > 0 && (
                    <div className="space-y-2">
                      {data.highlights.map((highlight, index) => (
                        <div key={index} className="flex items-start gap-2 text-sm">
                          <span className="text-primary">•</span>
                          <span>{highlight}</span>
                        </div>
                      ))}
                    </div>
                  )}
                  
                  <div className="flex items-center justify-between text-xs text-muted-foreground pt-2">
                    <span>Generated by Echo</span>
                    <Button 
                      variant="ghost" 
                      size="sm" 
                      className="h-6 text-xs"
                      onClick={onRefresh}
                    >
                      <RefreshCw className="h-3 w-3 mr-1" />
                      Refresh
                    </Button>
                  </div>
                </div>
              ) : (
                <p className="text-sm text-muted-foreground">
                  No briefing available yet. Your AI briefing will appear here.
                </p>
              )}
            </CardContent>
          </motion.div>
        )}
      </AnimatePresence>
    </Card>
  )
}

// ============================================================================
// MEETING PREP COMPONENT
// ============================================================================

function MeetingPrep({ meetings, loading }) {
  const [selectedMeeting, setSelectedMeeting] = useState(null)
  
  if (loading) {
    return (
      <Card>
        <CardContent className="py-4">
          <div className="flex items-center gap-2">
            <RefreshCw className="h-4 w-4 animate-spin" />
            <span className="text-sm">Loading meeting prep...</span>
          </div>
        </CardContent>
      </Card>
    )
  }
  
  const upcomingMeetings = meetings?.filter(m => m.prep) || []
  
  return (
    <Card>
      <CardHeader className="py-3 px-4">
        <div className="flex items-center gap-2">
          <Brain className="h-4 w-4 text-amber-500" />
          <CardTitle className="text-sm font-medium">Meeting Prep</CardTitle>
        </div>
      </CardHeader>
      <CardContent className="pt-0 pb-4 px-4">
        {upcomingMeetings.length > 0 ? (
          <div className="space-y-3">
            {upcomingMeetings.slice(0, 3).map((meeting, index) => (
              <div 
                key={index}
                className={cn(
                  "p-3 rounded-lg border cursor-pointer transition-all",
                  selectedMeeting === index 
                    ? "border-primary bg-primary/5" 
                    : "hover:border-primary/50"
                )}
                onClick={() => setSelectedMeeting(selectedMeeting === index ? null : index)}
              >
                <div className="flex items-start justify-between">
                  <div>
                    <p className="text-sm font-medium">{meeting.title}</p>
                    <p className="text-xs text-muted-foreground">
                      {new Date(meeting.start_time).toLocaleTimeString([], { 
                        hour: '2-digit', 
                        minute: '2-digit' 
                      })}
                      {meeting.attendees && ` • ${meeting.attendees.length} attendees`}
                    </p>
                  </div>
                  <Badge variant="secondary" className="text-xs">
                    <Sparkles className="h-3 w-3 mr-1" />
                    AI Prep
                  </Badge>
                </div>
                
                <AnimatePresence>
                  {selectedMeeting === index && meeting.prep && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      className="mt-3 pt-3 border-t"
                    >
                      {meeting.prep.context && (
                        <div className="mb-2">
                          <p className="text-xs font-medium text-muted-foreground mb-1">Context</p>
                          <p className="text-sm">{meeting.prep.context}</p>
                        </div>
                      )}
                      
                      {meeting.prep.talking_points?.length > 0 && (
                        <div className="mb-2">
                          <p className="text-xs font-medium text-muted-foreground mb-1">Talking Points</p>
                          <ul className="text-sm space-y-1">
                            {meeting.prep.talking_points.map((point, i) => (
                              <li key={i} className="flex items-start gap-2">
                                <Target className="h-3 w-3 mt-1 text-primary shrink-0" />
                                <span>{point}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                      
                      {meeting.prep.documents?.length > 0 && (
                        <div>
                          <p className="text-xs font-medium text-muted-foreground mb-1">Relevant Docs</p>
                          <div className="flex flex-wrap gap-1">
                            {meeting.prep.documents.map((doc, i) => (
                              <Badge key={i} variant="outline" className="text-xs cursor-pointer hover:bg-muted">
                                <FileText className="h-3 w-3 mr-1" />
                                {doc.name}
                              </Badge>
                            ))}
                          </div>
                        </div>
                      )}
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            ))}
          </div>
        ) : (
          <p className="text-sm text-muted-foreground">
            No upcoming meetings with AI prep available.
          </p>
        )}
      </CardContent>
    </Card>
  )
}

// ============================================================================
// FOCUS TIME COMPONENT
// ============================================================================

function FocusTime({ data, loading, onSchedule }) {
  if (loading) {
    return (
      <Card>
        <CardContent className="py-4">
          <div className="flex items-center gap-2">
            <RefreshCw className="h-4 w-4 animate-spin" />
            <span className="text-sm">Analyzing schedule...</span>
          </div>
        </CardContent>
      </Card>
    )
  }
  
  return (
    <Card>
      <CardHeader className="py-3 px-4">
        <div className="flex items-center gap-2">
          <Coffee className="h-4 w-4 text-emerald-500" />
          <CardTitle className="text-sm font-medium">Focus Time</CardTitle>
        </div>
      </CardHeader>
      <CardContent className="pt-0 pb-4 px-4">
        {data?.suggestions?.length > 0 ? (
          <div className="space-y-3">
            <p className="text-sm text-muted-foreground">
              {data.message || "Optimal focus blocks based on your schedule:"}
            </p>
            
            {data.suggestions.slice(0, 3).map((suggestion, index) => (
              <div 
                key={index}
                className="flex items-center justify-between p-2 rounded-lg bg-muted/50"
              >
                <div className="flex items-center gap-2">
                  <Clock className="h-4 w-4 text-muted-foreground" />
                  <div>
                    <p className="text-sm font-medium">{suggestion.label}</p>
                    <p className="text-xs text-muted-foreground">
                      {suggestion.start} - {suggestion.end}
                    </p>
                  </div>
                </div>
                <Button 
                  size="sm" 
                  variant="outline"
                  onClick={() => onSchedule?.(suggestion)}
                >
                  <Zap className="h-3 w-3 mr-1" />
                  Block
                </Button>
              </div>
            ))}
          </div>
        ) : (
          <div className="text-center py-4">
            <Coffee className="h-8 w-8 text-muted-foreground mx-auto mb-2" />
            <p className="text-sm text-muted-foreground">
              No focus time suggestions yet
            </p>
            <Button size="sm" variant="outline" className="mt-2">
              Find Focus Time
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  )
}

// ============================================================================
// AI INSIGHTS COMPONENT
// ============================================================================

function AIInsights({ insights, loading }) {
  if (loading || !insights?.length) return null
  
  return (
    <Card>
      <CardHeader className="py-3 px-4">
        <div className="flex items-center gap-2">
          <Lightbulb className="h-4 w-4 text-yellow-500" />
          <CardTitle className="text-sm font-medium">AI Insights</CardTitle>
        </div>
      </CardHeader>
      <CardContent className="pt-0 pb-4 px-4">
        <div className="space-y-2">
          {insights.slice(0, 3).map((insight, index) => (
            <div 
              key={index}
              className="flex items-start gap-2 p-2 rounded-lg bg-yellow-500/5 border border-yellow-500/20"
            >
              <Sparkles className="h-4 w-4 text-yellow-500 shrink-0 mt-0.5" />
              <p className="text-sm">{insight.message}</p>
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  )
}

// ============================================================================
// MAIN COMPONENT
// ============================================================================

export default function SignalAIPanel({ date, calendarData, onClose }) {
  const { user, currentProject } = useAuthStore()
  const [loading, setLoading] = useState(true)
  const [aiData, setAiData] = useState({
    briefing: null,
    focusTime: null,
    insights: []
  })
  
  // Fetch AI data
  useEffect(() => {
    const fetchAIData = async () => {
      if (!currentProject?.id) return
      
      setLoading(true)
      try {
        // Fetch all AI data in parallel
        const [briefing, focusTime] = await Promise.all([
          syncApi.getDailyBriefing(currentProject.id, date.toISOString()).catch(() => null),
          syncApi.getFocusTime(currentProject.id, date.toISOString()).catch(() => null)
        ])
        
        setAiData({
          briefing,
          focusTime,
          insights: briefing?.insights || []
        })
      } catch (error) {
        console.error('Failed to fetch AI data:', error)
      } finally {
        setLoading(false)
      }
    }
    
    fetchAIData()
  }, [currentProject?.id, date])
  
  // Get meetings with prep
  const meetingsWithPrep = calendarData?.events?.map(event => ({
    ...event,
    prep: event.ai_prep || null
  })) || []
  
  // Handle focus time scheduling
  const handleScheduleFocusTime = async (suggestion) => {
    try {
      await syncApi.blockFocusTime(currentProject?.id, {
        start: suggestion.start_time,
        end: suggestion.end_time,
        label: suggestion.label
      })
      // Refresh calendar data
    } catch (error) {
      console.error('Failed to block focus time:', error)
    }
  }

  return (
    <div className="h-full flex flex-col bg-muted/30">
      {/* Header */}
      <div className="p-4 border-b bg-background/80 backdrop-blur-sm">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="p-1.5 rounded-lg bg-primary/10">
              <Sparkles className="h-4 w-4 text-primary" />
            </div>
            <div>
              <h2 className="font-semibold text-sm">Echo AI</h2>
              <p className="text-xs text-muted-foreground">Calendar Intelligence</p>
            </div>
          </div>
          <Badge variant="secondary" className="text-xs">
            <Zap className="h-3 w-3 mr-1" />
            Signal
          </Badge>
        </div>
      </div>
      
      {/* Content */}
      <ScrollArea className="flex-1">
        <div className="p-4 space-y-4">
          {/* Daily Briefing */}
          <DailyBriefing 
            data={aiData.briefing} 
            loading={loading}
            onRefresh={() => {
              // Trigger refresh
            }}
          />
          
          {/* Meeting Prep */}
          <MeetingPrep 
            meetings={meetingsWithPrep}
            loading={loading}
          />
          
          {/* Focus Time */}
          <FocusTime 
            data={aiData.focusTime}
            loading={loading}
            onSchedule={handleScheduleFocusTime}
          />
          
          {/* AI Insights */}
          <AIInsights 
            insights={aiData.insights}
            loading={loading}
          />
        </div>
      </ScrollArea>
      
      {/* Footer */}
      <div className="p-3 border-t bg-background/80 backdrop-blur-sm">
        <p className="text-xs text-center text-muted-foreground">
          Powered by Echo • Signal AI
        </p>
      </div>
    </div>
  )
}
